commande:
    pattern:  /
    defaults: { _controller: "elinoixshopBundle:Commande:index" }

commande_show:
    pattern:  /{id}/show
    defaults: { _controller: "elinoixshopBundle:Commande:show" }

#commande_new:
#    pattern:  /new
#    defaults: { _controller: "elinoixshopBundle:Commande:new" }

commande_create:
    pattern:  /create
    defaults: { _controller: "elinoixshopBundle:Commande:create" }
    requirements: { _method: post }

commande_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "elinoixshopBundle:Commande:edit" }

commande_update:
    pattern:  /{id}/update
    defaults: { _controller: "elinoixshopBundle:Commande:update" }
    requirements: { _method: post|put }

commande_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "elinoixshopBundle:Commande:delete" }
    requirements: { _method: post|delete }


commande_validation:
    pattern:  /{id}/validation
    defaults: { _controller: "elinoixshopBundle:Commande:validation" }
    
commande_recap:
    pattern:  /{id}/recap
    defaults: { _controller: "elinoixshopBundle:Commande:recap" }
    
commande_recap_valider:
    pattern:  /{id}/recap/valider
    defaults: { _controller: "elinoixshopBundle:Commande:validerRecap" }
    
paiement_prepare:
    pattern:  /{id}/paiement/prepare
    defaults: { _controller: "elinoixshopBundle:Paiement:prepare" }
    
paiement_complete:
    pattern:  /{id}/paiement/complete
    defaults: { _controller: "elinoixshopBundle:Paiement:complete" }