produit:
    pattern:  /
    defaults: { _controller: "elinoixshopBundle:Produit:index" }

produit_show:
    pattern:  /{id}/show
    defaults: { _controller: "elinoixshopBundle:Produit:show" }

produit_new:
    pattern:  /new
    defaults: { _controller: "elinoixshopBundle:Produit:new" }

produit_create:
    pattern:  /create
    defaults: { _controller: "elinoixshopBundle:Produit:create" }
    requirements: { _method: post }

produit_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "elinoixshopBundle:Produit:edit" }

produit_update:
    pattern:  /{id}/update
    defaults: { _controller: "elinoixshopBundle:Produit:update" }
    requirements: { _method: post|put }

produit_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "elinoixshopBundle:Produit:delete" }
    requirements: { _method: post|delete }
