elinoixshop:
    resource: "@elinoixshopBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: elinoixshopBundle:Security:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout