elinoixshop:
    resource: "@elinoixshopBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: elinoixshopBundle:Security:login }
    
login_check:
    pattern: /login_check
    
logout:
    pattern: /logout
    
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    
payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    
payment_done:
    pattern:  /payment_done
    defaults: { _controller: "elinoixshopBundle:Paiement:captureDone" }