security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        login:
            pattern:   ^/(login$|register|resetting)
            anonymous: true       
        main:
            pattern: ^/                     # ^/ = tout ce qui commence par / = tout notre site
            anonymous: ~
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                csrf_provider: form.csrf_provider
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /index
                failure_path:   /login
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                check_path: /login_check
                use_forward: false
            logout:
                path:   /logout
                target: /login
                invalidate_session: false
            remember_me:
                key: %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
                path: /index
                lifetime: 5000
    access_control:
        - { path: "^/login_redirect$", roles: ROLE_USER }
        - { path: "^/produit/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/org/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/client/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/panier", roles: ROLE_USER }
        - { path: "^/org", roles: ROLE_ADMIN }
        - { path: "^/client", roles: ROLE_ADMIN }
        - { path: "^/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }

