security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        elinoix\shopBundle\Entity\Organisation: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        organisations:
            entity: { class: elinoixshopBundle:Organisation, property: login }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            firewalls:

        shop:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
               

    access_control:
        - { path: "^/login_redirect$", roles: ROLE_USER }
        - { path: "^/produit/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/org/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/client/[^/]+/show+/?$", roles: ROLE_USER }
        - { path: "^/panier", roles: ROLE_USER }
        - { path: "^/produit", roles: ROLE_ADMIN }
        - { path: "^/org", roles: ROLE_ADMIN }
        - { path: "^/client", roles: ROLE_ADMIN }
        - { path: "^/login", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
