<?php

namespace elinoix\shopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaypalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalOrderRepository extends EntityRepository
{
}
